from mt_simulator import MTSimulator

### top-down
print("-------- TOP_DOWN testing: --------")
print("/a")
mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a")
mt.read_traffic_from_file("traffic/traffic_1.txt")
print("FIB count:", mt.count_fib())

mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a")
mt.read_traffic_from_file("traffic/traffic_2.txt")
print("FIB count:", mt.count_fib())

mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a")
mt.read_traffic_from_file("traffic/traffic_3.txt")
print("FIB count:", mt.count_fib())

mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a")
mt.read_traffic_from_file("traffic/traffic_4.txt")
print("FIB count:", mt.count_fib())

print("/a/b1")
mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a/b1")
mt.read_traffic_from_file("traffic/traffic_1.txt")
print("FIB count:", mt.count_fib())

mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a/b1")
mt.read_traffic_from_file("traffic/traffic_2.txt")
print("FIB count:", mt.count_fib())

mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a/b1")
mt.read_traffic_from_file("traffic/traffic_3.txt")
print("FIB count:", mt.count_fib())

mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a/b1")
mt.read_traffic_from_file("traffic/traffic_4.txt")
print("FIB count:", mt.count_fib())


print("/a/b1/c1")
mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a/b1/c1")
mt.read_traffic_from_file("traffic/traffic_1.txt")
print("FIB count:", mt.count_fib())

mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a/b1/c1")
mt.read_traffic_from_file("traffic/traffic_2.txt")
print("FIB count:", mt.count_fib())

mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a/b1/c1")
mt.read_traffic_from_file("traffic/traffic_3.txt")
print("FIB count:", mt.count_fib())

mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a/b1/c1")
mt.read_traffic_from_file("traffic/traffic_4.txt")
print("FIB count:", mt.count_fib())

print("/a/b1/c1/d1")
mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a/b1/c1/d1")
mt.read_traffic_from_file("traffic/traffic_1.txt")
print("FIB count:", mt.count_fib())

mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a/b1/c1/d1")
mt.read_traffic_from_file("traffic/traffic_2.txt")
print("FIB count:", mt.count_fib())

mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a/b1/c1/d1")
mt.read_traffic_from_file("traffic/traffic_3.txt")
print("FIB count:", mt.count_fib())

mt = MTSimulator()
mt.insert_fib("/a","r1")
mt.update_or_insert_rank("r2", "/a/b1/c1/d1")
mt.read_traffic_from_file("traffic/traffic_4.txt")
print("FIB count:", mt.count_fib())